export const ENTITY_TYPES = {
    USER: "users",
    ADMIN: "admins",
    FAQ: "faqs",
    COMPANY: "company",
    JOB_POSTING: "job_posting",
    TERMS_AND_CONDITIONS: "terms_and_conditions",
    COUPONS: "coupons",
    MEMBERSHIPS: "memberships",
    UPDATES: "updates",
    MCQS: "mcqs",
    CHEATSHEETS: "cheatsheets",
    CATEGORIES: "categories",
    COURSE_TOPICS: "course_topics",
    COURSE_TOPIC_VIDEO: "course_topic_video",
    COURSE: "course",
    PROJECTS: "projects",
    RESUME_MASTERS: "resume_masters",
    WORKSHOPS: "workshops",
    REGISTRATIONS: "registrations",
};
