export const NOTIFICATION_TRIGGERS = {
    // ─────────────── BILLING & COUPONS ───────────────
    COUPON_CREATE: "COUPON_CREATE",
    COUPON_UPDATE: "COUPON_UPDATE",
    COUPON_ACTIVE: "COUPON_ACTIVE",
    COUPON_INACTIVE: "COUPON_INACTIVE",

    MEMBERSHIP_PLAN_CREATE: "MEMBERSHIP_PLAN_CREATE",
    MEMBERSHIP_PLAN_UPDATE: "MEMBERSHIP_PLAN_UPDATE",
    MEMBERSHIP_PLAN_ACTIVE: "MEMBERSHIP_PLAN_ACTIVE",
    MEMBERSHIP_PLAN_INACTIVE: "MEMBERSHIP_PLAN_INACTIVE",

    // ─────────────── RECRUITMENT & JOBS ───────────────
    COMPANY_PROFILE_CREATE: "COMPANY_PROFILE_CREATE",
    COMPANY_PROFILE_UPDATE: "COMPANY_PROFILE_UPDATE",
    COMAPNY_PROFILE_ACTIVE: "COMAPNY_PROFILE_ACTIVE",
    COMAPNY_PROFILE_INACTIVE: "COMAPNY_PROFILE_INACTIVE",

    JOB_POST: "JOB_POST",
    JOB_UPDATE: "JOB_UPDATE",
    JOB_INACTIVE: "JOB_INACTIVE",
    JOB_ACTIVE: "JOB_ACTIVE",

    // ─────────────── WORKSHOPS ───────────────
    WORKSHOP_CREATED: "WORKSHOP_CREATED",
    WORKSHOP_UPDATED: "WORKSHOP_UPDATED",
    WORKSHOP_INACTIVE: "WORKSHOP_INACTIVE",
    WORKSHOP_ACTIVE: "WORKSHOP_ACTIVE",

    // ─────────────── LEADS MANAGEMENT ───────────────
    LEAD_ASSIGNED: "LEAD_ASSIGNED",

    // ─────────────── COMMUNICATION & DISCUSSIONS ───────────────
    DISCUSSION_CREATED: "DISCUSSION_CREATED",
    USER_QUERY_CREATED: "USER_QUERY_CREATED",

    // ─────────────── USER MANAGEMENT ───────────────
    USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
    USER_PROFILE_INACTIVE: "USER_PROFILE_INACTIVE",
    USER_PROFILE_ACTIVE: "USER_PROFILE_ACTIVE",

    // ─────────────── ADMINS & ROLES ───────────────
    ADMIN_CREATE: "ADMIN_CREATE",
    ADMIN_PROFILE_UPDATE: "ADMIN_PROFILE_UPDATE",
    ADMIN_INACTIVE: "ADMIN_INACTIVE",
    ADMIN_ACTIVE: "ADMIN_ACTIVE",

    ROLE_CREATE: "ROLE_CREATE",
    ROLE_UPDATE: "ROLE_UPDATE",
    ROLE_ACTIVE: "ROLE_ACTIVE",
    ROLE_INACTIVE: "ROLE_INACTIVE",
};
