export const PERMISSIONS = {
    /********************************** Dashboard *********************************/
    UV_DASHBOARD: "UV_DASHBOARD",
    VIEW_DASHBOARD: "VIEW_DASHBOARD", // Keep for backward compatibility if needed

    UV_DASHBOARD_USERS: "UV_DASHBOARD_USERS",
    UV_DASHBOARD_LEADS: "UV_DASHBOARD_LEADS",
    UV_DASHBOARD_FINANCE: "UV_DASHBOARD_FINANCE",
    UV_DASHBOARD_JOB_POSTINGS: "UV_DASHBOARD_JOB_POSTINGS",
    UV_DASHBOARD_QUERY: "UV_DASHBOARD_QUERY",
    UV_DASHBOARD_AUDIT: "UV_DASHBOARD_AUDIT",
    UV_DASHBOARD_SUBMISSIONS: "UV_DASHBOARD_SUBMISSIONS",
    UV_DASHBOARD_DISCUSSIONS: "UV_DASHBOARD_DISCUSSIONS",
    UV_DASHBOARD_EMPLOYEE_REFERRALS: "UV_DASHBOARD_EMPLOYEE_REFERRALS",
    UV_DASHBOARD_MY_REFERRALS: "UV_DASHBOARD_MY_REFERRALS",
    UV_DASHBOARD_WEB_TRAFFIC: "UV_DASHBOARD_WEB_TRAFFIC",

    /********************************** User Management ***************************/
    UV_USER_MANAGEMENT: "UV_USER_MANAGEMENT",

    // User List Page
    UV_USERS_LIST: "UV_USERS_LIST",
    VIEW_USER_DETAILS: "VIEW_USER_DETAILS",
    EDIT_USER_DETAILS: "EDIT_USER_DETAILS",

    // Referral List Page
    UV_REFERRALS_LIST: "UV_REFERRALS_LIST",
    VIEW_REFERRAL_DETAILS: "VIEW_REFERRAL_DETAILS",

    // Employee Referrals
    UV_EMPLOYEE_REFERRALS: "UV_EMPLOYEE_REFERRALS",
    VIEW_EMPLOYEE_REFERRAL_DETAILS: "VIEW_EMPLOYEE_REFERRAL_DETAILS",
    EDIT_EMPLOYEE_REFERRAL_DETAILS: "EDIT_EMPLOYEE_REFERRAL_DETAILS",

    // My Referrals
    UV_MY_REFERRALS: "UV_MY_REFERRALS",
    ONBOARD_STUDENT: "ONBOARD_STUDENT",

    // Membership Users Page
    UV_MEMBERSHIP_USERS: "UV_MEMBERSHIP_USERS",

    /********************************** Admin Management **************************/
    UV_SYSTEM_ADMINISTRATION: "UV_SYSTEM_ADMINISTRATION",

    // Admin List Page
    UV_ADMINS_LIST: "UV_ADMINS_LIST",
    CREATE_ADMIN: "CREATE_ADMIN",
    RESEND_ADMIN_INVITE: "RESEND_ADMIN_INVITE",
    RESET_ADMIN_SESSION: "RESET_ADMIN_SESSION",
    VIEW_ADMIN_DETAILS: "VIEW_ADMIN_DETAILS",
    EDIT_ADMIN_DETAILS: "EDIT_ADMIN_DETAILS",
    DELETE_ADMIN_DETAILS: "DELETE_ADMIN_DETAILS",
    RESTORE_ADMIN_DETAILS: "RESTORE_ADMIN_DETAILS",

    // Role Management
    UV_ROLES_AND_PERMISSIONS: "UV_ROLES_AND_PERMISSIONS",
    CREATE_ROLE: "CREATE_ROLE",
    VIEW_ROLES: "VIEW_ROLES",
    EDIT_ROLES_AND_PERMISSIONS: "EDIT_ROLES_AND_PERMISSIONS",
    DELETE_ROLES_AND_PERMISSIONS: "DELETE_ROLES_AND_PERMISSIONS",

    /********************************** Audit Logs ********************************/
    UV_AUDIT_LOGS: "UV_AUDIT_LOGS",
    VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
    RESET_AUDIT_LOGS: "RESET_AUDIT_LOGS",
    EXPORT_AUDIT_LOGS: "EXPORT_AUDIT_LOGS",

    /********************************** Recruitment *******************************/
    UV_RECRUITMENT_MANAGEMENT: "UV_RECRUITMENT_MANAGEMENT",

    // Company Management
    UV_RECRUITMENT_COMPANIES: "UV_RECRUITMENT_COMPANIES",
    CREATE_COMPANY: "CREATE_COMPANY",
    VIEW_COMPANY_DETAILS: "VIEW_COMPANY_DETAILS",
    EDIT_COMPANY_DETAILS: "EDIT_COMPANY_DETAILS",
    DELETE_COMPANY_DETAILS: "DELETE_COMPANY_DETAILS",
    RESTORE_COMPANY_DETAILS: "RESTORE_COMPANY_DETAILS",

    // Job Postings
    UV_RECRUITMENT_JOB_POSTINGS: "UV_RECRUITMENT_JOB_POSTINGS",
    CREATE_JOB_POSTING: "CREATE_JOB_POSTING",
    VIEW_JOB_DETAILS: "VIEW_JOB_DETAILS",
    EDIT_JOB_DETAILS: "EDIT_JOB_DETAILS",
    DELETE_JOB_DETAILS: "DELETE_JOB_DETAILS",
    RESTORE_JOB_DETAILS: "RESTORE_JOB_DETAILS",

    // Candidates
    UV_RECRUITMENT_CANDIDATES: "UV_RECRUITMENT_CANDIDATES",
    VIEW_CANDIDATES: "VIEW_CANDIDATES",

    // Recruiters
    UV_RECRUITMENT_RECRUITERS: "UV_RECRUITMENT_RECRUITERS",
    VIEW_RECRUITER: "VIEW_RECRUITER",

    /********************************** Communication Center ********************/
    UV_COMMUNICATION_CENTER: "UV_COMMUNICATION_CENTER",

    // Query Center / Comments
    UV_QUERY_CENTER: "UV_QUERY_CENTER",
    VIEW_QUERY_CENTER: "VIEW_QUERY_CENTER",
    REPLY_QUERY: "REPLY_QUERY",

    // Feedback
    UV_FEEDBACK: "UV_FEEDBACK",

    // Discussions
    UV_DISCUSSIONS: "UV_DISCUSSIONS",
    VIEW_DISCUSSIONS: "VIEW_DISCUSSIONS",
    SEND_MESSAGE: "SEND_MESSAGE",

    // FAQs
    UV_FAQS: "UV_FAQS",
    CREATE_FAQ: "CREATE_FAQ",
    VIEW_FAQ_DETAILS: "VIEW_FAQ_DETAILS",
    EDIT_FAQ_DETAILS: "EDIT_FAQ_DETAILS",
    DELETE_FAQ_DETAILS: "DELETE_FAQ_DETAILS",
    RESTORE_FAQ_DETAILS: "RESTORE_FAQ_DETAILS",


    // OUTREACH
    UV_OUTREACH: "UV_OUTREACH",

    // Student Submissions
    UV_STUDENT_SUBMISSIONS: "UV_STUDENT_SUBMISSIONS",
    VIEW_SUBMISSION_DETAILS: "VIEW_SUBMISSION_DETAILS",
    REVIEW_SUBMISSION: "REVIEW_SUBMISSION",

    // Latest Updates & Upcoming Features
    UV_LATEST_UPDATES_AND_UPCOMING_FEATURES: "UV_LATEST_UPDATES_AND_UPCOMING_FEATURES",
    VIEW_LATEST_UPDATES_AND_UPCOMING_FEATURES: "VIEW_LATEST_UPDATES_AND_UPCOMING_FEATURES",
    CREATE_LATEST_UPDATES_AND_UPCOMING_FEATURES: "CREATE_LATEST_UPDATES_AND_UPCOMING_FEATURES",
    EDIT_LATEST_UPDATES_AND_UPCOMING_FEATURES: "EDIT_LATEST_UPDATES_AND_UPCOMING_FEATURES",
    DELETE_LATEST_UPDATES_AND_UPCOMING_FEATURES: "DELETE_LATEST_UPDATES_AND_UPCOMING_FEATURES",
    RESTORE_LATEST_UPDATES_AND_UPCOMING_FEATURES: "RESTORE_LATEST_UPDATES_AND_UPCOMING_FEATURES",

    /********************************** Learning Management *********************/
    UV_LEARNING_MANAGEMENT: "UV_LEARNING_MANAGEMENT",

    UV_MCQ_MANAGEMENT: "UV_MCQ_MANAGEMENT",
    CREATE_MCQ: "CREATE_MCQ",
    VIEW_MCQ_DETAILS: "VIEW_MCQ_DETAILS",
    EDIT_MCQ_DETAILS: "EDIT_MCQ_DETAILS",
    DELETE_MCQ_DETAILS: "DELETE_MCQ_DETAILS",
    RESTORE_MCQ_DETAILS: "RESTORE_MCQ_DETAILS",

    UV_CHEATSHEET_LIBRARY: "UV_CHEATSHEET_LIBRARY",
    CREATE_CHEATSHEET: "CREATE_CHEATSHEET",
    VIEW_CHEATSHEET_DETAILS: "VIEW_CHEATSHEET_DETAILS",
    EDIT_CHEATSHEET_DETAILS: "EDIT_CHEATSHEET_DETAILS",
    DELETE_CHEATSHEET_DETAILS: "DELETE_CHEATSHEET_DETAILS",
    RESTORE_CHEATSHEET_DETAILS: "RESTORE_CHEATSHEET_DETAILS",

    UV_COURSE_CATEGORIES: "UV_COURSE_CATEGORIES",
    CREATE_COURSE_CATEGORY: "CREATE_COURSE_CATEGORY",
    VIEW_COURSE_CATEGORY_DETAILS: "VIEW_COURSE_CATEGORY_DETAILS",
    EDIT_COURSE_CATEGORY_DETAILS: "EDIT_COURSE_CATEGORY_DETAILS",
    DELETE_COURSE_CATEGORY_DETAILS: "DELETE_COURSE_CATEGORY_DETAILS",
    RESTORE_COURSE_CATEGORY_DETAILS: "RESTORE_COURSE_CATEGORY_DETAILS",

    UV_COURSE_LIBRARY: "UV_COURSE_LIBRARY",
    CREATE_COURSE: "CREATE_COURSE",
    VIEW_COURSE_DETAILS: "VIEW_COURSE_DETAILS",
    EDIT_COURSE_DETAILS: "EDIT_COURSE_DETAILS",
    DELETE_COURSE_DETAILS: "DELETE_COURSE_DETAILS",
    RESTORE_COURSE_DETAILS: "RESTORE_COURSE_DETAILS",

    UV_RESUME_BUILDER: "UV_RESUME_BUILDER",
    CREATE_RESUME_BUILDER: "CREATE_RESUME_BUILDER",
    VIEW_RESUME_BUILDER: "VIEW_RESUME_BUILDER",
    EDIT_RESUME_BUILDER: "EDIT_RESUME_BUILDER",
    DELETE_RESUME_BUILDER: "DELETE_RESUME_BUILDER",
    RESTORE_RESUME_BUILDER: "RESTORE_RESUME_BUILDER",

    UV_PROJECT_DETAILS: "UV_PROJECT_DETAILS",
    CREATE_PROJECT: "CREATE_PROJECT",
    VIEW_PROJECT_DETAILS: "VIEW_PROJECT_DETAILS",
    EDIT_PROJECT_DETAILS: "EDIT_PROJECT_DETAILS",
    DELETE_PROJECT_DETAILS: "DELETE_PROJECT_DETAILS",
    RESTORE_PROJECT_DETAILS: "RESTORE_PROJECT_DETAILS",

    UV_WORKSHOPS: "UV_WORKSHOPS",
    CREATE_WORKSHOP: "CREATE_WORKSHOP",
    VIEW_WORKSHOP_DETAILS: "VIEW_WORKSHOP_DETAILS",
    EDIT_WORKSHOP_DETAILS: "EDIT_WORKSHOP_DETAILS",
    DELETE_WORKSHOP: "DELETE_WORKSHOP",

    /********************************** Billing & Subscriptions *****************/
    UV_BILLING_SUBSCRIPTIONS: "UV_BILLING_SUBSCRIPTIONS",

    // Coupons
    UV_DISCOUNT_COUPONS: "UV_DISCOUNT_COUPONS",
    CREATE_COUPON: "CREATE_COUPON",
    VIEW_COUPONS: "VIEW_COUPONS",
    EDIT_COUPONS: "EDIT_COUPONS",
    DELETE_COUPONS: "DELETE_COUPONS",
    RESTORE_COUPONS: "RESTORE_COUPONS",

    // Transactions
    UV_PAYMENT_TRANSACTIONS: "UV_PAYMENT_TRANSACTIONS",
    VIEW_TRANSACTION: "VIEW_TRANSACTION",

    // Membership Plans
    UV_MEMBERSHIP_PLANS: "UV_MEMBERSHIP_PLANS",
    CREATE_MEMBERSHIP_PLAN: "CREATE_MEMBERSHIP_PLAN",
    VIEW_MEMBERSHIP_DETAILS: "VIEW_MEMBERSHIP_DETAILS",
    EDIT_MEMBERSHIP_DETAILS: "EDIT_MEMBERSHIP_DETAILS",
    DELETE_MEMBERSHIP_DETAILS: "DELETE_MEMBERSHIP_DETAILS",
    RESTORE_MEMBERSHIP_DETAILS: "RESTORE_MEMBERSHIP_DETAILS",

    /********************************** Legal & Compliance **********************/
    UV_LEGAL_COMPLIANCE: "UV_LEGAL_COMPLIANCE",
    CREATE_LEGAL: "CREATE_LEGAL",
    VIEW_LEGAL: "VIEW_LEGAL",
    EDIT_LEGAL: "EDIT_LEGAL",
    DELETE_LEGAL: "DELETE_LEGAL",
    RESTORE_LEGAL: "RESTORE_LEGAL",

    /********************************** Leads Management ************************/
    UV_LEADS_MANAGEMENT: "UV_LEADS_MANAGEMENT",
    UV_LEADS_LIST: "UV_LEADS_LIST",
    VIEW_LEAD: "VIEW_LEAD",
    CREATE_LEAD: "CREATE_LEAD",
    EDIT_LEAD: "EDIT_LEAD",
    NOTES_LEAD: "NOTES_LEAD",
    EXPORT_LEAD: "EXPORT_LEAD",
    IMPORT_LEAD: "IMPORT_LEAD",
};
